import type { User, Invitation } from '../models/User.model';
import type { Organization } from '../models/Organization.model';
import type { Platform, PlatformForMe, Module, PlatformRole } from '../models/Platform.model';
import type { AccessGrant, Permission } from '../models/Access.model';
import type { Document } from '../models/Document.model';
import type { AuditLog, Notification, StatsOverview } from '../models/AuditLog.model';

export const MOCK_USERS: User[] = [
  {
    id: 'u-1',
    email: 'admin@ent.local',
    first_name: 'Thomas',
    last_name: 'Dupont',
    full_name: 'Thomas Dupont',
    username: 'tdupont',
    role: 'super_admin',
    phone: '+33 1 40 50 60 70',
    photo: null,
    organization: 'org-1',
    organization_name: 'Direction ENT',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-1',
    has_pending_invitation: false,
    last_login: new Date().toISOString(),
    date_joined: '2024-01-15T09:00:00Z',
  },
  {
    id: 'u-2',
    email: 'sophie.martin@ac-paris.fr',
    first_name: 'Sophie',
    last_name: 'Martin',
    full_name: 'Sophie Martin',
    username: 'smartin',
    role: 'org_admin',
    phone: '+33 1 42 00 11 22',
    photo: null,
    organization: 'org-2',
    organization_name: 'Académie de Paris',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-2',
    has_pending_invitation: false,
    last_login: '2026-09-25T14:30:00Z',
    date_joined: '2024-02-01T10:00:00Z',
  },
  {
    id: 'u-3',
    email: 'support@ent.local',
    first_name: 'Lucas',
    last_name: 'Bernard',
    full_name: 'Lucas Bernard',
    username: 'lbernard',
    role: 'support',
    phone: '+33 1 40 50 60 88',
    photo: null,
    organization: 'org-1',
    organization_name: 'Direction ENT',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-3',
    has_pending_invitation: false,
    last_login: '2026-09-26T08:15:00Z',
    date_joined: '2024-03-10T11:00:00Z',
  },
  {
    id: 'u-4',
    email: 'emilie.leroy@ac-paris.fr',
    first_name: 'Émilie',
    last_name: 'Leroy',
    full_name: 'Émilie Leroy',
    username: 'eleroy',
    role: 'client_user',
    phone: '+33 1 42 00 33 44',
    photo: null,
    organization: 'org-2',
    organization_name: 'Académie de Paris',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-4',
    has_pending_invitation: false,
    last_login: '2026-09-24T16:45:00Z',
    date_joined: '2024-04-05T09:30:00Z',
  },
  {
    id: 'u-5',
    email: 'marc.moreau@lycee-voltaire.fr',
    first_name: 'Marc',
    last_name: 'Moreau',
    full_name: 'Marc Moreau',
    username: 'mmoreau',
    role: 'prospect',
    phone: '+33 1 43 22 55 66',
    photo: null,
    organization: 'org-3',
    organization_name: 'Lycée Voltaire',
    is_active: true,
    is_suspended: false,
    keycloak_sub: null,
    has_pending_invitation: true,
    last_login: null,
    date_joined: '2026-09-20T14:00:00Z',
  },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Direction ENT',
    code: 'DIR-ENT',
    org_type: 'internal',
    email: 'contact@ent.local',
    phone: '+33 1 40 50 60 00',
    address: '10 Rue de Grenelle, 75007 Paris',
    country: 'France',
    logo: null,
    website: 'https://ent.local',
    status: 'active',
    users_count: 5,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-01T12:00:00Z',
  },
  {
    id: 'org-2',
    name: 'Académie de Paris',
    code: 'AC-PARIS',
    org_type: 'client',
    email: 'contact@ac-paris.fr',
    phone: '+33 1 42 00 00 00',
    address: '12 Boulevard d\'Indochine, 75019 Paris',
    country: 'France',
    logo: null,
    website: 'https://www.ac-paris.fr',
    status: 'active',
    users_count: 42,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2026-09-10T10:00:00Z',
  },
  {
    id: 'org-3',
    name: 'Lycée Voltaire',
    code: 'LYC-VOLTAIRE',
    org_type: 'prospect',
    email: 'direction@lycee-voltaire.fr',
    phone: '+33 1 43 22 00 00',
    address: '101 Avenue de la République, 75011 Paris',
    country: 'France',
    logo: null,
    website: 'https://lycee-voltaire.fr',
    status: 'active',
    users_count: 8,
    created_at: '2026-08-15T00:00:00Z',
    updated_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'org-4',
    name: 'Université Numérique',
    code: 'UNIV-NUM',
    org_type: 'partner',
    email: 'partenariats@univ-num.fr',
    phone: '+33 1 45 67 89 00',
    address: '25 Rue Claude Bernard, 75005 Paris',
    country: 'France',
    logo: null,
    website: 'https://univ-num.fr',
    status: 'active',
    users_count: 15,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-09-20T16:00:00Z',
  },
];

export const MOCK_MODULES: Module[] = [
  { id: 'm-1', platform: 'plat-1', name: 'Cours en ligne', code: 'COURS', description: 'Gestion des cours et modules pédagogiques', order: 1 },
  { id: 'm-2', platform: 'plat-1', name: 'Évaluations', code: 'EVAL', description: 'Examens, devoirs et suivi des notes', order: 2 },
  { id: 'm-3', platform: 'plat-2', name: 'Fichiers & Partage', code: 'FILES', description: 'Stockage cloud sécurisé et partage documentaire', order: 1 },
  { id: 'm-4', platform: 'plat-3', name: 'Salles virtuelles', code: 'ROOMS', description: 'Gestion des réunions et classes virtuelles', order: 1 },
];

export const MOCK_PLATFORM_ROLES: PlatformRole[] = [
  { id: 'pr-1', platform: 'plat-1', code: 'teacher', label: 'Enseignant / Formateur' },
  { id: 'pr-2', platform: 'plat-1', code: 'student', label: 'Étudiant / Apprenant' },
  { id: 'pr-3', platform: 'plat-2', code: 'editor', label: 'Éditeur de documents' },
  { id: 'pr-4', platform: 'plat-3', code: 'moderator', label: 'Modérateur de séance' },
];

export const MOCK_PLATFORMS: Platform[] = [
  {
    id: 'plat-1',
    name: 'Moodle LMS',
    code: 'MOODLE',
    description: 'Plateforme pédagogique d\'apprentissage en ligne et suivi des parcours scolaires.',
    logo: null,
    url: 'https://moodle.ent.local',
    environment: 'production',
    status: 'active',
    version: '4.4.1',
    released_at: '2026-01-10T00:00:00Z',
    sso_client_id: 'moodle-sso',
    modules: [MOCK_MODULES[0], MOCK_MODULES[1]],
    roles: [MOCK_PLATFORM_ROLES[0], MOCK_PLATFORM_ROLES[1]],
    active_access_grants_count: 54,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'plat-2',
    name: 'Nextcloud Espace',
    code: 'NEXTCLOUD',
    description: 'Stockage partagé, synchronisation de fichiers et travail collaboratif sécurisé.',
    logo: null,
    url: 'https://cloud.ent.local',
    environment: 'production',
    status: 'active',
    version: '29.0.2',
    released_at: '2026-02-15T00:00:00Z',
    sso_client_id: 'nextcloud-sso',
    modules: [MOCK_MODULES[2]],
    roles: [MOCK_PLATFORM_ROLES[2]],
    active_access_grants_count: 78,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2026-09-05T00:00:00Z',
  },
  {
    id: 'plat-3',
    name: 'BigBlueButton Visio',
    code: 'BBB',
    description: 'Salles de classe virtuelles et réunions en visioconférence haute définition.',
    logo: null,
    url: 'https://visio.ent.local',
    environment: 'production',
    status: 'active',
    version: '3.0.0',
    released_at: '2026-03-01T00:00:00Z',
    sso_client_id: 'bbb-sso',
    modules: [MOCK_MODULES[3]],
    roles: [MOCK_PLATFORM_ROLES[3]],
    active_access_grants_count: 31,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2026-09-12T00:00:00Z',
  },
  {
    id: 'plat-4',
    name: 'Esup-Pod Vidéothèque',
    code: 'ESUP_POD',
    description: 'Hébergement, diffusion et sous-titrage automatique de capsules vidéo pédagogiques.',
    logo: null,
    url: 'https://pod.ent.local',
    environment: 'staging',
    status: 'maintenance',
    version: '3.5.2',
    released_at: '2026-04-10T00:00:00Z',
    sso_client_id: 'pod-sso',
    modules: [],
    roles: [],
    active_access_grants_count: 12,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2026-09-24T00:00:00Z',
  },
];

export const MOCK_PLATFORMS_FOR_ME: PlatformForMe[] = MOCK_PLATFORMS.map((p) => ({
  id: p.id,
  name: p.name,
  code: p.code,
  description: p.description,
  logo: p.logo,
  url: p.url,
  version: p.version,
  status: p.status,
  expires_at: '2026-12-31T23:59:59Z',
  modules: p.modules,
  access_grant_id: `grant-${p.id}`,
}));

export const MOCK_ACCESS_GRANTS: AccessGrant[] = [
  {
    id: 'grant-1',
    user: 'u-2',
    user_name: 'Sophie Martin',
    user_email: 'sophie.martin@ac-paris.fr',
    platform: 'plat-1',
    platform_name: 'Moodle LMS',
    modules: ['m-1', 'm-2'],
    platform_role: 'pr-1',
    platform_role_label: 'Enseignant / Formateur',
    access_type: 'client',
    status: 'active',
    start_date: '2024-09-01T00:00:00Z',
    end_date: '2027-08-31T00:00:00Z',
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2024-09-01T08:00:00Z',
  },
  {
    id: 'grant-2',
    user: 'u-4',
    user_name: 'Émilie Leroy',
    user_email: 'emilie.leroy@ac-paris.fr',
    platform: 'plat-2',
    platform_name: 'Nextcloud Espace',
    modules: ['m-3'],
    platform_role: 'pr-3',
    platform_role_label: 'Éditeur de documents',
    access_type: 'client',
    status: 'active',
    start_date: '2024-09-01T00:00:00Z',
    end_date: '2027-08-31T00:00:00Z',
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2024-09-01T08:30:00Z',
  },
  {
    id: 'grant-3',
    user: 'u-5',
    user_name: 'Marc Moreau',
    user_email: 'marc.moreau@lycee-voltaire.fr',
    platform: 'plat-1',
    platform_name: 'Moodle LMS',
    modules: ['m-1'],
    platform_role: 'pr-2',
    platform_role_label: 'Étudiant / Apprenant',
    access_type: 'demo',
    status: 'active',
    start_date: '2026-09-20T00:00:00Z',
    end_date: new Date(Date.now() + 2 * 86_400_000).toISOString(),
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'grant-4',
    user: 'u-5',
    user_name: 'Marc Moreau',
    user_email: 'marc.moreau@lycee-voltaire.fr',
    platform: 'plat-3',
    platform_name: 'BigBlueButton Visio',
    modules: ['m-4'],
    platform_role: 'pr-4',
    platform_role_label: 'Modérateur de séance',
    access_type: 'demo',
    status: 'active',
    start_date: '2026-09-20T00:00:00Z',
    end_date: new Date(Date.now() + 1 * 86_400_000).toISOString(),
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2026-09-20T10:30:00Z',
  },
  {
    id: 'grant-5',
    user: 'u-4',
    user_name: 'Émilie Leroy',
    user_email: 'emilie.leroy@ac-paris.fr',
    platform: 'plat-4',
    platform_name: 'Esup-Pod Vidéothèque',
    modules: [],
    platform_role: null,
    access_type: 'demo',
    status: 'expired',
    start_date: '2026-08-01T00:00:00Z',
    end_date: '2026-08-31T00:00:00Z',
    is_currently_valid: false,
    created_by: 'u-1',
    created_at: '2026-08-01T09:00:00Z',
  },
];

export const MOCK_PERMISSIONS: Permission[] = [
  { id: 'p-1', module: 'm-1', module_name: 'Cours en ligne', platform_name: 'Moodle LMS', action: 'VIEW' },
  { id: 'p-2', module: 'm-1', module_name: 'Cours en ligne', platform_name: 'Moodle LMS', action: 'CREATE' },
  { id: 'p-3', module: 'm-2', module_name: 'Évaluations', platform_name: 'Moodle LMS', action: 'VIEW' },
  { id: 'p-4', module: 'm-3', module_name: 'Fichiers & Partage', platform_name: 'Nextcloud Espace', action: 'VIEW' },
  { id: 'p-5', module: 'm-3', module_name: 'Fichiers & Partage', platform_name: 'Nextcloud Espace', action: 'UPDATE' },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc-1',
    platform: 'plat-1',
    platform_name: 'Moodle LMS',
    title: 'Guide d\'accueil des formateurs Moodle',
    category: 'manuel',
    description: 'Documentation pas à pas pour la création et le déploiement d\'espaces de cours.',
    status: 'published',
    current_version: {
      id: 'dv-1',
      document: 'doc-1',
      version_label: '2.1',
      file: '#',
      changelog: 'Mise à jour pour Moodle 4.4',
      is_current: true,
      published_at: '2026-02-01T10:00:00Z',
      created_at: '2026-02-01T09:30:00Z',
    },
    versions_count: 3,
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'doc-2',
    platform: 'plat-2',
    platform_name: 'Nextcloud Espace',
    title: 'Manuel d\'utilisation Nextcloud & Partages',
    category: 'manuel',
    description: 'Bonnes pratiques pour le partage de fichiers et les permissions des répertoires d\'équipe.',
    status: 'published',
    current_version: {
      id: 'dv-2',
      document: 'doc-2',
      version_label: '1.4',
      file: '#',
      changelog: 'Ajout de la section chiffrement',
      is_current: true,
      published_at: '2026-03-15T14:00:00Z',
      created_at: '2026-03-15T11:00:00Z',
    },
    versions_count: 2,
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2026-03-15T14:00:00Z',
  },
  {
    id: 'doc-3',
    platform: 'plat-3',
    platform_name: 'BigBlueButton Visio',
    title: 'Guide de démarrage rapide Visioconférence',
    category: 'guide_demarrage',
    description: 'Comment configurer son micro, sa caméra et partager son écran lors d\'une session.',
    status: 'published',
    current_version: {
      id: 'dv-3',
      document: 'doc-3',
      version_label: '1.0',
      file: '#',
      changelog: 'Version initiale',
      is_current: true,
      published_at: '2026-01-20T11:00:00Z',
      created_at: '2026-01-20T10:00:00Z',
    },
    versions_count: 1,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T11:00:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    actor: 'u-1',
    actor_name: 'Thomas Dupont',
    actor_email: 'admin@ent.local',
    action: 'Connexion SSO réussie',
    target_type: 'User',
    target_id: 'u-1',
    metadata: { provider: 'Keycloak OIDC', realm: 'ent' },
    ip_address: '192.168.1.45',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    created_at: new Date(Date.now() - 10 * 60_000).toISOString(),
  },
  {
    id: 'log-2',
    actor: 'u-1',
    actor_name: 'Thomas Dupont',
    actor_email: 'admin@ent.local',
    action: 'Création d\'un accès démo',
    target_type: 'AccessGrant',
    target_id: 'grant-3',
    metadata: { user: 'Marc Moreau', platform: 'Moodle LMS', duration_days: 7 },
    ip_address: '192.168.1.45',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    created_at: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: 'log-3',
    actor: 'u-2',
    actor_name: 'Sophie Martin',
    actor_email: 'sophie.martin@ac-paris.fr',
    action: 'Modification d\'utilisateur',
    target_type: 'User',
    target_id: 'u-4',
    metadata: { updated_fields: ['phone'] },
    ip_address: '82.124.50.12',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    created_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
  {
    id: 'log-4',
    actor: 'system',
    actor_name: 'Système ENT',
    actor_email: null,
    action: 'Expiration automatique d\'accès démo',
    target_type: 'AccessGrant',
    target_id: 'grant-5',
    metadata: { reason: 'date_limit_reached' },
    ip_address: '127.0.0.1',
    user_agent: 'Internal Worker Cron',
    created_at: new Date(Date.now() - 48 * 3600_000).toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    notif_type: 'info',
    title: 'Bienvenue sur l\'ENT',
    body: 'Votre espace de travail est prêt. Découvrez vos plateformes associées depuis le tableau de bord.',
    is_read: false,
    related_access_grant: null,
    created_at: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: 'notif-2',
    notif_type: 'warning',
    title: 'Démonstration arrivant à échéance',
    body: 'L\'accès démo de Marc Moreau sur Moodle LMS expire dans 2 jours.',
    is_read: false,
    related_access_grant: 'grant-3',
    created_at: new Date(Date.now() - 4 * 3600_000).toISOString(),
  },
  {
    id: 'notif-3',
    notif_type: 'success',
    title: 'Mise à jour de la documentation',
    body: 'Le guide formateur Moodle v2.1 a été publié.',
    is_read: true,
    related_access_grant: null,
    created_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
];

export const MOCK_STATS_OVERVIEW: StatsOverview = {
  users_count: 70,
  organizations_count: 4,
  platforms_count: 4,
  documents_count: 3,
  active_access_grants: 175,
  expired_access_grants: 12,
  active_demos: 2,
  expired_demos: 1,
  logins_today: 48,
  most_accessed_platforms: [
    { name: 'Moodle LMS', code: 'MOODLE', grant_count: 54 },
    { name: 'Nextcloud Espace', code: 'NEXTCLOUD', grant_count: 78 },
    { name: 'BigBlueButton Visio', code: 'BBB', grant_count: 31 },
    { name: 'Esup-Pod Vidéothèque', code: 'ESUP_POD', grant_count: 12 },
  ],
};

export const MOCK_INVITATIONS: Invitation[] = [
  {
    id: 'inv-1',
    user: 'u-5',
    user_full_name: 'Marc Moreau',
    email: 'marc.moreau@lycee-voltaire.fr',
    organization: 'org-3',
    organization_name: 'Lycée Voltaire',
    role: 'prospect',
    invited_by: 'Thomas Dupont',
    token: 'mock-invitation-token-12345',
    status: 'pending',
    expires_at: new Date(Date.now() + 7 * 86_400_000).toISOString(),
    created_at: new Date().toISOString(),
  },
];
