import type { User, Invitation } from '../models/User.model';
import type { Organization } from '../models/Organization.model';
import type { Platform, PlatformForMe, Module, PlatformRole } from '../models/Platform.model';
import type { AccessGrant, Permission } from '../models/Access.model';
import type { Document } from '../models/Document.model';
import type { AuditLog, Notification, StatsOverview } from '../models/AuditLog.model';

export const MOCK_USERS: User[] = [
  {
    id: 'u-1',
    email: 'admin@ent.local',
    first_name: 'Thomas',
    last_name: 'Dupont',
    full_name: 'Thomas Dupont',
    username: 'tdupont',
    role: 'super_admin',
    phone: '+33 1 40 50 60 70',
    photo: null,
    organization: 'org-1',
    organization_name: 'Direction ENT',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-1',
    has_pending_invitation: false,
    last_login: new Date().toISOString(),
    date_joined: '2024-01-15T09:00:00Z',
  },
  {
    id: 'u-2',
    email: 'sophie.martin@ac-paris.fr',
    first_name: 'Sophie',
    last_name: 'Martin',
    full_name: 'Sophie Martin',
    username: 'smartin',
    role: 'org_admin',
    phone: '+33 1 42 00 11 22',
    photo: null,
    organization: 'org-2',
    organization_name: 'Académie de Paris',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-2',
    has_pending_invitation: false,
    last_login: '2026-09-25T14:30:00Z',
    date_joined: '2024-02-01T10:00:00Z',
  },
  {
    id: 'u-3',
    email: 'support@ent.local',
    first_name: 'Lucas',
    last_name: 'Bernard',
    full_name: 'Lucas Bernard',
    username: 'lbernard',
    role: 'support',
    phone: '+33 1 40 50 60 88',
    photo: null,
    organization: 'org-1',
    organization_name: 'Direction ENT',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-3',
    has_pending_invitation: false,
    last_login: '2026-09-26T08:15:00Z',
    date_joined: '2024-03-10T11:00:00Z',
  },
  {
    id: 'u-4',
    email: 'emilie.leroy@ac-paris.fr',
    first_name: 'Émilie',
    last_name: 'Leroy',
    full_name: 'Émilie Leroy',
    username: 'eleroy',
    role: 'client_user',
    phone: '+33 1 42 00 33 44',
    photo: null,
    organization: 'org-2',
    organization_name: 'Académie de Paris',
    is_active: true,
    is_suspended: false,
    keycloak_sub: 'kc-sub-4',
    has_pending_invitation: false,
    last_login: '2026-09-24T16:45:00Z',
    date_joined: '2024-04-05T09:30:00Z',
  },
  {
    id: 'u-5',
    email: 'marc.moreau@lycee-voltaire.fr',
    first_name: 'Marc',
    last_name: 'Moreau',
    full_name: 'Marc Moreau',
    username: 'mmoreau',
    role: 'prospect',
    phone: '+33 1 43 22 55 66',
    photo: null,
    organization: 'org-3',
    organization_name: 'Lycée Voltaire',
    is_active: true,
    is_suspended: false,
    keycloak_sub: null,
    has_pending_invitation: true,
    last_login: null,
    date_joined: '2026-09-20T14:00:00Z',
  },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Direction ENT',
    code: 'DIR-ENT',
    org_type: 'internal',
    email: 'contact@ent.local',
    phone: '+33 1 40 50 60 00',
    address: '10 Rue de Grenelle, 75007 Paris',
    country: 'France',
    logo: null,
    website: 'https://ent.local',
    status: 'active',
    users_count: 5,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-09-01T12:00:00Z',
  },
  {
    id: 'org-2',
    name: 'Académie de Paris',
    code: 'AC-PARIS',
    org_type: 'client',
    email: 'contact@ac-paris.fr',
    phone: '+33 1 42 00 00 00',
    address: '12 Boulevard d\'Indochine, 75019 Paris',
    country: 'France',
    logo: null,
    website: 'https://www.ac-paris.fr',
    status: 'active',
    users_count: 42,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2026-09-10T10:00:00Z',
  },
  {
    id: 'org-3',
    name: 'Lycée Voltaire',
    code: 'LYC-VOLTAIRE',
    org_type: 'prospect',
    email: 'direction@lycee-voltaire.fr',
    phone: '+33 1 43 22 00 00',
    address: '101 Avenue de la République, 75011 Paris',
    country: 'France',
    logo: null,
    website: 'https://lycee-voltaire.fr',
    status: 'active',
    users_count: 8,
    created_at: '2026-08-15T00:00:00Z',
    updated_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'org-4',
    name: 'Université Numérique',
    code: 'UNIV-NUM',
    org_type: 'partner',
    email: 'partenariats@univ-num.fr',
    phone: '+33 1 45 67 89 00',
    address: '25 Rue Claude Bernard, 75005 Paris',
    country: 'France',
    logo: null,
    website: 'https://univ-num.fr',
    status: 'active',
    users_count: 15,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-09-20T16:00:00Z',
  },
];

export const MOCK_MODULES: Module[] = [
  { id: 'm-1', platform: 'plat-1', name: 'Module CVB', code: 'CVB', description: 'Commandes, Ventes et Bons de réquisition de fournitures', order: 1 },
  { id: 'm-2', platform: 'plat-1', name: 'Module Admin', code: 'ADM', description: 'Gestion des stocks, articles et inventaires', order: 2 },
  { id: 'm-3', platform: 'plat-2', name: 'Émission de timbres', code: 'EMISSION', description: 'Achat et émission de timbres certifiés QR code', order: 1 },
  { id: 'm-4', platform: 'plat-3', name: 'Inventaire Matériel', code: 'INVENTAIRE', description: 'Suivi du parc et des affectations', order: 1 },
  { id: 'm-5', platform: 'plat-4', name: 'Comptabilité Budgétaire', code: 'BUDGET', description: 'Engagements et mandatements de dépenses', order: 1 },
];

export const MOCK_PLATFORM_ROLES: PlatformRole[] = [
  { id: 'pr-1', platform: 'plat-1', code: 'admin', label: 'Administrateur Economat' },
  { id: 'pr-2', platform: 'plat-1', code: 'user', label: 'Agent Demandeur CVB' },
  { id: 'pr-3', platform: 'plat-2', code: 'operator', label: 'Opérateur Guichet' },
  { id: 'pr-4', platform: 'plat-3', code: 'tech', label: 'Gestionnaire de Parc' },
  { id: 'pr-5', platform: 'plat-4', code: 'comptable', label: 'Agent Comptable' },
];

export const MOCK_PLATFORMS: Platform[] = [
  {
    id: 'plat-1',
    name: 'Economat',
    code: 'ECO',
    description: 'Gestion des approvisionnements, réquisitions de fournitures (CVB) et gestion des stocks (Admin).',
    logo: null,
    url: 'https://economat.tpe.bf/',
    environment: 'production',
    status: 'active',
    version: '1.0.0',
    released_at: '2026-01-10T00:00:00Z',
    sso_client_id: 'economat-frontend',
    modules: [MOCK_MODULES[0], MOCK_MODULES[1]],
    roles: [MOCK_PLATFORM_ROLES[0], MOCK_PLATFORM_ROLES[1]],
    active_access_grants_count: 85,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'plat-2',
    name: 'E-Timbre',
    code: 'ET',
    description: 'Dématérialisation fiscale, émission et vérification des timbres par QR code infalsifiable.',
    logo: null,
    url: 'https://etimbre.tpe.bf/home/',
    environment: 'production',
    status: 'active',
    version: '2.1.0',
    released_at: '2026-02-15T00:00:00Z',
    sso_client_id: 'etimbre-frontend',
    modules: [MOCK_MODULES[2]],
    roles: [MOCK_PLATFORM_ROLES[2]],
    active_access_grants_count: 64,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2026-09-05T00:00:00Z',
  },
  {
    id: 'plat-3',
    name: 'Parc Manager',
    code: 'PM',
    description: 'Inventaire automatisé du parc informatique, affectations nominatives et tickets de maintenance.',
    logo: null,
    url: 'https://parcmanager.tpe.bf/login',
    environment: 'production',
    status: 'active',
    version: '1.5.0',
    released_at: '2026-03-01T00:00:00Z',
    sso_client_id: 'parcmanager-frontend',
    modules: [MOCK_MODULES[3]],
    roles: [MOCK_PLATFORM_ROLES[3]],
    active_access_grants_count: 42,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2026-09-12T00:00:00Z',
  },
  {
    id: 'plat-4',
    name: 'SGI-GCOB',
    code: 'GCOB',
    description: 'Système de gestion intégré et comptabilité budgétaire pour l\'ordonnancement et les mandatements.',
    logo: null,
    url: 'https://gcob.mzeba.dev/login/?next=/',
    environment: 'production',
    status: 'active',
    version: '2.0.0',
    released_at: '2026-04-10T00:00:00Z',
    sso_client_id: 'gcob-frontend',
    modules: [MOCK_MODULES[4]],
    roles: [MOCK_PLATFORM_ROLES[4]],
    active_access_grants_count: 38,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2026-09-24T00:00:00Z',
  },
];

export const MOCK_PLATFORMS_FOR_ME: PlatformForMe[] = MOCK_PLATFORMS.map((p) => ({
  id: p.id,
  name: p.name,
  code: p.code,
  description: p.description,
  logo: p.logo,
  url: p.url,
  version: p.version,
  status: p.status,
  expires_at: '2026-12-31T23:59:59Z',
  modules: p.modules,
  access_grant_id: `grant-${p.id}`,
}));

export const MOCK_ACCESS_GRANTS: AccessGrant[] = [
  {
    id: 'grant-1',
    user: 'u-2',
    user_name: 'Sophie Martin',
    user_email: 'sophie.martin@ac-paris.fr',
    platform: 'plat-1',
    platform_name: 'Economat',
    modules: ['m-1', 'm-2'],
    platform_role: 'pr-1',
    platform_role_label: 'Administrateur Economat',
    access_type: 'client',
    status: 'active',
    start_date: '2024-09-01T00:00:00Z',
    end_date: '2027-08-31T00:00:00Z',
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2024-09-01T08:00:00Z',
  },
  {
    id: 'grant-2',
    user: 'u-4',
    user_name: 'Émilie Leroy',
    user_email: 'emilie.leroy@ac-paris.fr',
    platform: 'plat-2',
    platform_name: 'E-Timbre',
    modules: ['m-3'],
    platform_role: 'pr-3',
    platform_role_label: 'Opérateur Guichet',
    access_type: 'client',
    status: 'active',
    start_date: '2024-09-01T00:00:00Z',
    end_date: '2027-08-31T00:00:00Z',
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2024-09-01T08:30:00Z',
  },
  {
    id: 'grant-3',
    user: 'u-5',
    user_name: 'Marc Moreau',
    user_email: 'marc.moreau@lycee-voltaire.fr',
    platform: 'plat-1',
    platform_name: 'Economat',
    modules: ['m-1'],
    platform_role: 'pr-2',
    platform_role_label: 'Agent Demandeur CVB',
    access_type: 'client',
    status: 'active',
    start_date: '2026-09-20T00:00:00Z',
    end_date: new Date(Date.now() + 365 * 86_400_000).toISOString(),
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'grant-4',
    user: 'u-5',
    user_name: 'Marc Moreau',
    user_email: 'marc.moreau@lycee-voltaire.fr',
    platform: 'plat-3',
    platform_name: 'Parc Manager',
    modules: ['m-4'],
    platform_role: 'pr-4',
    platform_role_label: 'Gestionnaire de Parc',
    access_type: 'client',
    status: 'active',
    start_date: '2026-09-20T00:00:00Z',
    end_date: new Date(Date.now() + 365 * 86_400_000).toISOString(),
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2026-09-20T10:30:00Z',
  },
  {
    id: 'grant-5',
    user: 'u-4',
    user_name: 'Émilie Leroy',
    user_email: 'emilie.leroy@ac-paris.fr',
    platform: 'plat-4',
    platform_name: 'SGI-GCOB',
    modules: ['m-5'],
    platform_role: 'pr-5',
    platform_role_label: 'Agent Comptable',
    access_type: 'client',
    status: 'active',
    start_date: '2026-08-01T00:00:00Z',
    end_date: '2027-08-31T00:00:00Z',
    is_currently_valid: true,
    created_by: 'u-1',
    created_at: '2026-08-01T09:00:00Z',
  },
];

export const MOCK_PERMISSIONS: Permission[] = [
  { id: 'p-1', module: 'm-1', module_name: 'Module CVB', platform_name: 'Economat', action: 'VIEW' },
  { id: 'p-2', module: 'm-1', module_name: 'Module CVB', platform_name: 'Economat', action: 'CREATE' },
  { id: 'p-3', module: 'm-2', module_name: 'Module Admin', platform_name: 'Economat', action: 'UPDATE' },
  { id: 'p-4', module: 'm-3', module_name: 'Émission de timbres', platform_name: 'E-Timbre', action: 'VIEW' },
  { id: 'p-5', module: 'm-4', module_name: 'Inventaire Matériel', platform_name: 'Parc Manager', action: 'VIEW' },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '9dd08a45-cbce-476d-b300-946e0854cefa',
    platform: 'plat-1',
    platform_name: 'Economat',
    title: 'Manuel d\'utilisation Economat (APEC)',
    category: 'manuel',
    description: 'Documentation pas à pas pour la gestion des réquisitions CVB, le suivi des stocks et l\'administration.',
    status: 'published',
    current_version: {
      id: 'dv-1',
      document: '9dd08a45-cbce-476d-b300-946e0854cefa',
      version_label: '1.0',
      file: '/documents/APEC_Manuel_dutilisation_admin_APEC.pdf',
      changelog: 'Version initiale de production',
      is_current: true,
      published_at: '2026-02-01T10:00:00Z',
      created_at: '2026-02-01T09:30:00Z',
    },
    versions_count: 1,
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'f2a8d3d8-01b9-4583-a0c3-1cc56035eee7',
    platform: 'plat-1',
    platform_name: 'Economat',
    title: 'Cahier des charges APEC (MedScan Enterprise)',
    category: 'notes_version',
    description: 'Spécifications d\'interopérabilité technique, connecteurs OpenID Connect / Keycloak et conformité TLS 1.3.',
    status: 'published',
    current_version: {
      id: 'dv-2',
      document: 'f2a8d3d8-01b9-4583-a0c3-1cc56035eee7',
      version_label: '1.0',
      file: '/documents/MedScan_Enterprise_Cahier_des_Charges_Ekrdqz8.pdf',
      changelog: 'Validation des spécifications architecturales',
      is_current: true,
      published_at: '2026-03-15T14:00:00Z',
      created_at: '2026-03-15T11:00:00Z',
    },
    versions_count: 1,
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2026-03-15T14:00:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    actor: 'u-1',
    actor_name: 'Thomas Dupont',
    actor_email: 'admin@ent.local',
    action: 'Connexion SSO réussie',
    target_type: 'User',
    target_id: 'u-1',
    metadata: { provider: 'Keycloak OIDC', realm: 'ent' },
    ip_address: '192.168.1.45',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    created_at: new Date(Date.now() - 10 * 60_000).toISOString(),
  },
  {
    id: 'log-2',
    actor: 'u-1',
    actor_name: 'Thomas Dupont',
    actor_email: 'admin@ent.local',
    action: 'Création d\'un accès démo',
    target_type: 'AccessGrant',
    target_id: 'grant-3',
    metadata: { user: 'Marc Moreau', platform: 'Parc Manager', duration_days: 7 },
    ip_address: '192.168.1.45',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    created_at: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: 'log-3',
    actor: 'u-2',
    actor_name: 'Sophie Martin',
    actor_email: 'sophie.martin@ac-paris.fr',
    action: 'Modification d\'utilisateur',
    target_type: 'User',
    target_id: 'u-4',
    metadata: { updated_fields: ['phone'] },
    ip_address: '82.124.50.12',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    created_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
  {
    id: 'log-4',
    actor: 'system',
    actor_name: 'Système ENT',
    actor_email: null,
    action: 'Expiration automatique d\'accès démo',
    target_type: 'AccessGrant',
    target_id: 'grant-5',
    metadata: { reason: 'date_limit_reached' },
    ip_address: '127.0.0.1',
    user_agent: 'Internal Worker Cron',
    created_at: new Date(Date.now() - 48 * 3600_000).toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    notif_type: 'info',
    title: 'Bienvenue sur l\'ENT',
    body: 'Votre espace de travail est prêt. Découvrez vos plateformes associées depuis le tableau de bord.',
    is_read: false,
    related_access_grant: null,
    created_at: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: 'notif-2',
    notif_type: 'warning',
    title: 'Renouvellement d\'habilitation',
    body: 'L\'accès de Marc Moreau sur Parc Manager arrive à échéance prochainement.',
    is_read: false,
    related_access_grant: 'grant-3',
    created_at: new Date(Date.now() - 4 * 3600_000).toISOString(),
  },
  {
    id: 'notif-3',
    notif_type: 'success',
    title: 'Mise à jour de la documentation',
    body: 'Le manuel d\'utilisation Economat v1.0 a été publié.',
    is_read: true,
    related_access_grant: null,
    created_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
];

export const MOCK_STATS_OVERVIEW: StatsOverview = {
  users_count: 70,
  organizations_count: 4,
  platforms_count: 4,
  documents_count: 2,
  active_access_grants: 175,
  expired_access_grants: 12,
  active_demos: 0,
  expired_demos: 0,
  logins_today: 48,
  most_accessed_platforms: [
    { name: 'Economat', code: 'ECO', grant_count: 85 },
    { name: 'E-Timbre', code: 'ET', grant_count: 64 },
    { name: 'Parc Manager', code: 'PM', grant_count: 42 },
    { name: 'SGI-GCOB', code: 'GCOB', grant_count: 38 },
  ],
};

export const MOCK_INVITATIONS: Invitation[] = [
  {
    id: 'inv-1',
    user: 'u-5',
    user_full_name: 'Marc Moreau',
    email: 'marc.moreau@lycee-voltaire.fr',
    organization: 'org-3',
    organization_name: 'Lycée Voltaire',
    role: 'prospect',
    invited_by: 'Thomas Dupont',
    token: 'mock-invitation-token-12345',
    status: 'pending',
    expires_at: new Date(Date.now() + 7 * 86_400_000).toISOString(),
    created_at: new Date().toISOString(),
  },
];
